# This file is templated by Terraform using templatefile()
# The following variables are substituted at deployment time:
#   ${node_iam_role_name} - IAM role name created for nodes
#   ${cluster_name} - EKS cluster name from variables
#   ${vpc_id} - VPC ID where the cluster is deployed
#   ${additional_sg_id} - Additional security group ID (if created)
#   ${subnet_ids} - JSON array of subnet IDs
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: basic
spec:
  # IAM role for nodes (substituted by Terraform)
  role: "${node_iam_role_name}"
  
  # Subnet selection - use explicit subnet IDs
  subnetSelectorTerms:
    - id: ${subnet_ids}
  
  # Security group selection - use cluster security group and additional SG
  securityGroupSelectorTerms:
    - tags:
        "aws:eks:cluster-name": "${cluster_name}"
%{ if additional_sg_id != "" ~}
    - id: "${additional_sg_id}"
%{ endif ~}
  
  ephemeralStorage:
    size: "100Gi"    # Range: 1-9000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000
  
  tags:
    Environment: "production"
    Team: "platform"
